### ISSUE TITLE
My sweet theme to imageGlass

### ISSUE THREAD

**Issue by eterchronos** [ImageGlass/theme#11]
[Constellation.zip](https://github.com/ImageGlass/Theme/files/11631702/Constellation.zip)

**Comment by d2phap** [comment]
Thanks @eterchronos for the theme!

I have published it to: https://imageglass.org/theme/Constellation-Eterchronos-50
Your theme pack is also kept here: https://github.com/ImageGlass/Theme/tree/main/themes/dark/Constellation.Eterchronos
