### ISSUE TITLE
Dead URL in Create-theme-for-v8.md

### ISSUE THREAD

**Issue by Guiorgy** [ImageGlass/theme#14]
The example `igtheme.xml` url leads to `404` (https://github.com/ImageGlass/theme/blob/master/themes/dark/2017_dark/igtheme.xml).

It should either should be updated to point to a new location (e.g. https://github.com/ImageGlass/Theme/blob/main/themes/dark/2017-Ocean.Duong-Dieu-Phap/igtheme.xml), or preferably to a specific commit, since the example is for an outdated format that should no longer be receiving updates (e.g. https://github.com/ImageGlass/Theme/blob/e0c9176fc1f75474b72289238f9e05c0e8d12739/themes/dark/2017-Ocean.Duong-Dieu-Phap/igtheme.xml). I'm not sure which commit would be best, so I didn't create a PR.

**Comment by d2phap** [comment]
Thanks @Guiorgy! I just updated
