### ISSUE TITLE
Line(gray) Theme  for ImageGlass 8.x

### ISSUE THREAD

**Issue by xkonglong** [ImageGlass/theme#3]
![preview 1](https://user-images.githubusercontent.com/9131496/103493816-81717e80-4e6e-11eb-916f-7ad279d3bdb2.png)

[Line(Gray).zip](https://github.com/ImageGlass/theme/files/5762607/Line.Gray.zip)

**Comment by d2phap** [comment]
Thanks @xkonglong 
I will check and share on IG website

**Comment by d2phap** [comment]
Hi @xkonglong 
Your theme is missing icons in Page Navigation tool, do you want to update it?

![image](https://user-images.githubusercontent.com/3154213/103543532-a3ecb180-4ed9-11eb-8ca7-31b2aa24b877.png)


![image](https://user-images.githubusercontent.com/3154213/103543387-6556f700-4ed9-11eb-978f-1c364b5ebd2c.png)

**Comment by xkonglong** [comment]
@d2phap 

`uploadfb="facebook.svg" extension="extension.svg" settings="setting.svg" about="" menu="menu.svg" double-left-chevron="double-left.svg" double-right-chevron="double-right.svg" />`

ver 1.2
[Line(Gray).zip](https://github.com/ImageGlass/theme/files/5768786/Line.Gray.zip)

**Comment by d2phap** [comment]
Hi @xkonglong 

I posted your theme pack to IG website.
Thanks for sharing!

https://imageglass.org/theme/line-gray-38

**Comment by xkonglong** [comment]
[Line (Gray).zip](https://github.com/ImageGlass/theme/files/7681758/Line.Gray.zip)

Fix ZoomIn & ZoomOut error.

**Comment by xkonglong** [comment]
@d2phap

**Comment by d2phap** [comment]
Thanks @xkonglong 
I updated on IG website: https://imageglass.org/theme/line-gray-38
Next time you can create a new issue :)
