### ISSUE TITLE
Webp animated file opens 80 pages instead of showing animated picture

### ISSUE THREAD

**Issue by AnonymisedFellow** [ImageGlass/theme#4]
like the title says

**Comment by AnonymisedFellow** [comment]
![image](https://user-images.githubusercontent.com/24274546/104755908-5a168d80-575b-11eb-96f4-2a28563c3f64.png)

**Comment by d2phap** [comment]
Please refer to this ticket:

https://github.com/d2phap/ImageGlass/issues/508
