### ISSUE TITLE
Roka - ImageGlass theme

### ISSUE THREAD

**Issue by WOOB4T** [ImageGlass/theme#5]
![preview](https://user-images.githubusercontent.com/59617656/115457153-fd27e900-a21b-11eb-97b5-824c6b6aeed7.jpg)

[Roka.zip](https://github.com/ImageGlass/theme/files/6346379/Roka.zip)

**Comment by d2phap** [comment]
Uploaded to https://imageglass.org/theme/roka-39!

Thanks @WOOB4T
