### ISSUE TITLE
Dracula - ImageGlass theme for 8.x

### ISSUE THREAD

**Issue by FelkonEXE** [ImageGlass/theme#7]
![preview](https://user-images.githubusercontent.com/12007786/116776480-f9ae2080-aaab-11eb-9d9b-41f19cc306c5.jpg)

[Dracula.zip](https://github.com/ImageGlass/theme/files/6409159/Dracula.zip)

**Comment by FelkonEXE** [comment]
And here's the actual `.igtheme` file zipped up
[Dracula.zip](https://github.com/ImageGlass/theme/files/6409163/Dracula.zip)

**Comment by d2phap** [comment]
Thanks @FelkonEx 
I noticed you forked `ImageGlass/theme` to https://github.com/FelkonEx/Dracula-ImageGlass, and you have an awesome website of Dracula themes collection.

You can create a release on your `FelkonEx/Dracula-ImageGlass`, then let me know, I will get the download link from your repo,
(similar to https://github.com/marnick-s/material-imageglass-themes/releases), and post to ImageGlass website.
This way lets you know your own download count (by GitHub).

**Comment by FelkonEXE** [comment]
Sure thing! Repo's most likely gonna be transferred under [https://github.com/dracula](https://github.com/dracula) once it's accepted by those guys, but I'll be sure to let you know when!

**Comment by d2phap** [comment]
I saw your repo, and share the Dracula theme on ImageGlass website: https://imageglass.org/theme/dracula-43
Thanks!
