### ISSUE TITLE
Outdated theme

### ISSUE THREAD

**Issue by Sakujes** [ImageGlass/theme#8]
The [Green Gradient](https://imageglass.org/theme/green-gradient-26) theme is listed as Compatibility 8.0, but is [missing some icons](https://github.com/ImageGlass/theme/tree/master/themes/dark/Green-Gradient.Duong-Dieu-Phap) from that ImageGlass version, like Cropping (Crop.svg) and Scale to fill (ScaleToFill.svg). I am not an artist so my PR would be useless, but an update from anyone would be really appreciated :)

**Comment by d2phap** [comment]
I updated all missing icons of Green Gradient theme pack. 
https://imageglass.org/theme/green-gradient-26

Enjoy!
