### ISSUE TITLE
Colibre infinity 20px (Edit for who like dark theme)

### ISSUE THREAD

**Issue by rinme** [ImageGlass/theme#9]
[https://github.com/rinme/Other-Things/raw/main/Colibre%20infinity%2020px%20(dark%20Edit).igtheme](url)

**I Edited for a little**
**I edited this because it kinda Bright like discord light theme**

i did this like [https://github.com/ImageGlass/theme/blob/master/README.md](url)

Preview : 
![image](https://user-images.githubusercontent.com/56862783/126048314-74602e77-570a-4a4c-9411-eaf2644f5b94.png)

**Comment by d2phap** [comment]
Thanks @rinme 
I uploaded it to: https://imageglass.org/theme/colibre-infinity-20px-dark-edit-44

I also changed the selected menu text color from white to black for better contrast
